Fix @SafeVarargs annotation on listOf method
@SafeVarargs can only be used on final methods or static methods.
Since listOf is an instance method, it must be declared final.

This resolves compilation error:
"Invalid java.lang.SafeVarargs annotation. Instance method <T>listOf(T...)
is not final."